#!/usr/bin/env bash

echo "🔁 Switching IP ... "
echo "Current IP: $(curl -s api.ipify.org)"
echo "🔻 Deactivating current connection ... "
warp-cli registration delete
# echo "✅ Deactivated current connection ... "
echo "😴 Sleeping for 2 seconds ... "
sleep 2
echo "🔼 Registering new connection ... "
warp-cli registration new
# echo "✅ Registered new connection ... "
echo "🔗 Connecting ... "
warp-cli connect
echo "😴 Sleeping for 2 seconds ... "
sleep 2
echo "🔍 Checking status of warp ... "
warp-cli status
echo "🔍 Checking new IP ... $(curl -s api.ipify.org) "
echo "✅ Done ... "
