#!/usr/bin/env bash

. $HOME/scripts/activate_ve 've'
python -m fire machineconfig.scripts.python.choose_wezterm_theme main
source ~/.bashrc  # reload the profile
if [ -n "$VIRTUAL_ENV" ]; then
  deactivate || true

fi
