#!/usr/bin/env bash

op_script=$HOME/tmp_results/shells/python_return_command.sh
if [ -f "$op_script" ]; then
  rm $op_script
fi


. $HOME/scripts/activate_ve 've'

python $(dirname $(dirname $0))/python/cloud_repo_sync.py "$@"

if [ -f "$op_script" ]; then
  chmod +x $op_script
  source $op_script
fi


if [ -n "$VIRTUAL_ENV" ]; then
  deactivate || true

fi
