#!/usr/bin/env bash

# source activate_ve.sh
source ~/venvs/ve/bin/activate
python -m machineconfig.scripts.python.devops $@
chmod +x ~/tmp_results/shells/python_return_command.sh
source ~/tmp_results/shells/python_return_command.sh
