#!/usr/bin/env bash

source ~/code/machineconfig/.venv/bin/activate

op_script=$HOME/tmp_results/shells/python_return_command.sh
if [ -f "$op_script" ]; then
  rm $op_script
fi

# uv run --no-dev --project ~/code/machineconfig python -m machineconfig.scripts.python.devops "$@"
python -m machineconfig.scripts.python.devops "$@"

if [ -f "$op_script" ]; then
  chmod +x $op_script
  source $op_script
fi


# check below if VIRTUAL_ENV enviroment variable exist, then deactivate it, other wise skip
if [ -n "$VIRTUAL_ENV" ]; then
  deactivate
fi
