#!/usr/bin/env bash
uv run --no-dev --project $HOME/code/machineconfig python -m machineconfig.scripts.python.devops "$@"
# uv run --with machineconfig python -m machineconfig.scripts.python.devops "$@"
