#!/bin/bash

dir_orig=$(pwd)

if [ -d "$HOME/dotfiles/config/setup/rclone_remote" ]; then
    echo "Path $HOME/dotfiles/config/setup/rclone_remote does not exist. Aborting"
    exit 1
fi

rclone_remote=$(cat "$HOME/dotfiles/config/setup/rclone_remote")

echo ""
echo "=============================== Downloading Remote Repo ===================================="
mkdir -p ~/.machineconfig/sync_dotfiles
rm -rdf ~/.machineconfig/sync_dotfiles
cloud_rx "$rclone_remote" myhome/generic_os/dotfiles -zew -l ~/.machineconfig/sync_dotfiles  # overwrite, zip and encrypt
mv ~/.machineconfig/dotfiles ~/.machineconfig/sync_dotfiles

echo ""
echo "=============================== Pulling Remote Repo ===================================="
cd ~/dotfiles || exit
git remote remove origin
git remote add origin "$HOME/.machineconfig/sync_dotfiles"

if git pull origin master; then
    echo ""
    echo "Pull succeeded, removing local copy of remote ... "
    rm -rf ~/.machineconfig/sync_dotfiles/*
else
    echo ""
    echo "Pull failed. Check the remote @ ~/.machineconfig/sync_dotfiles"
fi

cd "$dir_orig" || exit
