#!/usr/bin/env bash

. $HOME/scripts/activate_ve 've'

python -c "from machineconfig.utils.procs import ProcessManager; ProcessManager().choose_and_kill()"

if [ -n "$VIRTUAL_ENV" ]; then
  deactivate || true

fi
