#!/usr/bin/env bash

. ~/scripts/activate_ve 've'

python -m machineconfig.jobs.python.create_zellij_template

zellij --layout $HOME/tmp_results/tmp_files/templates/zellij_template.kdl

deactivate || true

