#!/usr/bin/bash

#sess_name=$(cat ~/dotfiles/creds/tmate/$1)
#api_key=$(cat ~/dotfiles/creds/tmate/api_key)
#tmate -a ~/.ssh/authorized_keys -k $api_key -n $sess_name -F
# use sslh and shellinthebox to cirumvent the need for port forwarding
pyfile=~/code/machineconfig/src/machineconfig/scripts/python/tmate_start.py
# TODO make this path relevant to current file ($0)
python3 $pyfile $1
deactivate || true