#!/usr/bin/env bash

# Mount on linux
# Lsblk
# sudo apt install dislocker

lsblk
# read device name from user input and choose default value of sdb1
read -p "Enter device name (default: sdb1): " device
# if user input is empty, set device to sdb1
device=${device:-sdb1}
read -p "Enter mount name (default: mymnt): " mnt_name
mnt_name=${mnt_name:-mymnt}

# Make sure to create the mounting directory.  # Mkdir /media/mymnt
sudo mkdir -p /media/bitlocker
sudo mkdir -p /media/mymnt

# check if drive is bitlocker
#sudo dislocker -V /dev/$device

# If drive is bitlocker , following: https://www.linuxuprising.com/2019/04/how-to-mount-bitlocker-encrypted.html
sudo dislocker /dev/$device -u -- /media/bitlocker # Will be prompted for password (-u)


# sudo mount -o loop /media/bitlocker/dislocker-file /media/bitlockermount
# Modified from here to fix permissions: https://askubuntu.com/questions/1045057/i-cant-write-only-read-on-usb-device-encrypted-with-bitlocker
# sudo mount --source /dev/sdb1 --target /media/bitlocker
sudo mount -o loop,rw,uid=1000,gid=1000 /media/bitlocker/dislocker-file /media/$mnt_name

