# adopted from https://github.com/helix-editor/helix/wiki/Language-Server-Configurations
# adopted from https://github.com/helix-editor/helix/discussions/6623
# You will need: uv add --dev pylsp-mypy python-lsp-server[all] pyright ruff-lsp

[[language]]
name = "python"
language-servers = ["pylsp", "pyright", "ruff", "pyrefly"]

[language-server.pyrefly]
command = "pyrefly"
args = [ "lsp" ]

[language-server.pylsp.config.pylsp]
plugins.pylsp_mypy.enabled = true
plugins.pylsp_mypy.live_mode = true


[language-server.pyright.config.python.analysis]
typeCheckingMode = "strict"

[language-server.ruff]
command = "ruff-lsp"

# https://docs.astral.sh/ruff/configuration/
# [language-server.ruff.config.settings]
# args = ["--ignore", "E501"]
# args = ["--ignore", "E701,E702,F541,E721"]

[language.formatter]
command = "black"
args = ["--line-length", "88", "--quiet", "-"]
