def pomodoro(work: int = 25, rest: int = 5, repeats: int = 4):
    # ...existing code...
    print(f"\n{'=' * 60}\n⏲️  POMODORO | Session started with {work}min work, {rest}min rest, {repeats} cycles\n{'=' * 60}\n")
    # ...existing code...
    print(f"\n{'=' * 60}\n✅ COMPLETED | Pomodoro session finished successfully\n{'=' * 60}\n")
    # ...existing code...
