def pomodoro(work: int = 25, rest: int = 5, repeats: int = 4):
    # ...existing code...
    print("⏲️ Pomodoro started...")
    # ...existing code...
    print("✅ Pomodoro completed.")
    # ...existing code...
