
FROM statistician:machineconfig-slim


# Set bash as default shell
SHELL ["/bin/bash", "-lc"]

RUN /root/.local/bin/devops install --group agents

# Clean up of installer files.
RUN rm -rfd /root/tmp_results
RUN /root/.local/bin/uv clean && \
    rm -rfd /root/.cache/pip && \
    npm cache clean --force

WORKDIR /root
CMD ["/usr/bin/bash"]
