
[mgr]
show_hidden = true
ratio = [1, 3, 5]

[plugin]
dir = "~/.config/yazi/plugins"

[[plugin.load]]
name = "toggle-pane"
path = "toggle-pane.yazi"


[preview]
# Change them to your desired values
max_width  = 1000
max_height = 1000
