#!/usr/bin/env bash

# https://tmate.io/
#api_key=echo ~/dotfiles/creds/tmate/api_key
#sess_name=echo ~/dotfiles/creds/tmate/$1
#ssh $username/$sess_name@sgp1.tmate.io

. ~/scripts/activate_ve ''
machineconfig_path=$(python -c "print(__import__('machineconfig').__file__[:-12])")
pyfile=$machineconfig_path/scripts/python/tmate_conn.py
# TODO make this path relevant to current file ($0)
python3 $pyfile $1
deactivate || true
