#!/usr/bin/bash

#sess_name=$(cat ~/dotfiles/creds/tmate/$1)
#api_key=$(cat ~/dotfiles/creds/tmate/api_key)
#tmate -a ~/.ssh/authorized_keys -k $api_key -n $sess_name -F
# use sslh and shellinthebox to cirumvent the need for port forwarding

. $HOME/scripts/activate_ve ''
machineconfig_path=$(python -c "print(__import__('machineconfig').__file__[:-12])")
pyfile=$machineconfig_path/scripts/python/tmate_start.py
python3 $pyfile $1
deactivate || true
